### ISSUE TITLE
비트맵 저장소를 바꾸면 비트맵 정보를 읽지 못함

### ISSUE THREAD

**Issue by sunghwan2789** [sunghwan2789/osu-Lyrics#13]
osu! 설치 폴더 내 osu!.username.cfg에서
BeatmapDirectory = A_PATH_OTHER_THAN_Songs
1를 위처럼 Songs 외의 값으로 설정하면 ....
어디 갔니.. 비트맵...

**Comment by ArtBlnd** [comment]
그럼 간단히 레지스트리로부터 osu 폴더를 찾아낸 후에 cfg파일 읽어서 하면되잖수!

**Comment by sunghwan2789** [comment]
힉... 프로그램 소스 고칠거얌!
꼼짝마 ㅡㅡ@

**Comment by ArtBlnd** [comment]
확막 처음부터 다시짜버림!?!?!??!?

**Comment by sunghwan2789** [comment]
ㅎㅎ;

**Comment by ArtBlnd** [comment]
일단 제가 이번주까지 최대한 코드정리 + 최적화 + 버그수정에 최대한 힘쓸게요
