### ISSUE TITLE
osu!Lyrics 종료시 dll eject 안 됨

### ISSUE THREAD

**Issue by sunghwan2789** [sunghwan2789/osu-Lyrics#14]
eb5c2d8204dc2cf140664083eb75a3702daca9cd

freelibrary를 https://github.com/sunghwan2789/osu-Lyrics/blob/eb5c2d8204dc2cf140664083eb75a3702daca9cd/osu!Lyrics/Osu.cs#L278
이렇게 하는 게 아니였누..

**Comment by ArtBlnd** [comment]
VirtualFreeEx(hProcess, pHModule, 0, MEM_RELEASE); 이거빼주세요.

**Comment by ArtBlnd** [comment]
WriteProcessMemory(hProcess, pHModule, BitConverter.ToString(BitConverter.GetBytes(hinstDLL)), 4, IntPtr.Zero); 그리고 스트링으로 컨버팅하시면안됩니다. 그냥 hinstDLL를 써주세요

**Comment by ArtBlnd** [comment]
hinstDLL을 말씀 드렷듯이 IntPtr로 받아주시고. IntPtr 상태로 그대로 입력되야만함

**Comment by ArtBlnd** [comment]
일단 이거 건들이지말아주세요 제가 dll 메뉴얼로 inject하게 만들테니까 건들지 말아주세요.
함수사용안하고 전부 메뉴얼로 메모리할당받아서 수동으로 패치할겁니다.

**Comment by sunghwan2789** [comment]
dll 인젝트 부분은 안 건들도록 하지..!

**Comment by sunghwan2789** [comment]
but intended at master branch!!

**Comment by ArtBlnd** [comment]
이부분 dll 내부에서 스레드로 dll 자신을 디젝트하는방법도있네요 동생 컴퓨터줘야되서 3시간뒤에 시도해볼게요.

**Comment by ArtBlnd** [comment]
새로운 엔진에서 해결할 예정.

**Comment by ArtBlnd** [comment]
곧 DLL Shared Section을 사용해서 해결할 예정.
