### ISSUE TITLE
자막 싱크오류

### ISSUE THREAD

**Issue by ArtBlnd** [sunghwan2789/osu-Lyrics#16]
곡을 매인화면에서 중지시켰는데도 불구하고 계속 자막이 흘러가네요.
아마 만약에 문제라면 오스상의 문제일수도있을것같아요. 그만 중지시켰는데도 계속 파일을 읽는

**Comment by ArtBlnd** [comment]
일시정지 한정이더군요. 그냥 중지는 괜찮네요

**Comment by sunghwan2789** [comment]
오스 상의 문제이다

**Comment by ArtBlnd** [comment]
고칠방법은 없는건가.. 흐음... 일단 페피한테 문의해볼게요

**Comment by sunghwan2789** [comment]
근데 osu!Lyrics가 곡이 멈췄는지 아닌지 모를 거임

**Comment by ArtBlnd** [comment]
방법이 없는건 아니니 찾아보겠음!

**Comment by ArtBlnd** [comment]
이거 곡 타임스템프만 알면 되는건가요? 후킹헤서 필요한 정보가?

**Comment by sunghwan2789** [comment]
ㅇㅇ 현재 재생 중인 곡의 타임

**Comment by ArtBlnd** [comment]
그럼 차라리 오디오 라이브러리를 후킹하는게 나을것같네요

**Comment by sunghwan2789** [comment]
그러고 싶었다... 맨 처음엔...
능력 부족이라 ReadFile 후킹으로 대충 파싱했었음

**Comment by ArtBlnd** [comment]
방법똑같음 오디오 Dll이름찾고 그에관련된 함수 정보 인터넷에서 찾아서 후킹하면됨

**Comment by ArtBlnd** [comment]
이건일단 제가 처리해봄

**Comment by ArtBlnd** [comment]
ㄴㄴ 이거 오스문제아님; 제대로 후킹해보고 여러가지방법으로도 해봄. 중지상태는 파일 리드안함 일단.

**Comment by ArtBlnd** [comment]
http://puu.sh/khCGb/0348210175.png 찾았다!!

**Comment by sunghwan2789** [comment]
뭐야 이게 ㅋㅋㅋㅋ

**Comment by ArtBlnd** [comment]
디스어셈블리해서 진짜 씹노가다해서 stop play 하는부분 찾음

**Comment by ArtBlnd** [comment]
http://puu.sh/khCQn/34fcec1391.png

**Comment by ArtBlnd** [comment]
그레서 이제 Stop 하는지 Play하는지 알수있음 ㅋㅋㅋ SetPoitsion으로 어디부분 플레이하는지도 알수있음.

**Comment by ArtBlnd** [comment]
저에게 칭찬과 관심을 주시죠 헥헥

**Comment by sunghwan2789** [comment]
헉ㅋㅋ VS에 저런 기능 있는지도 몰랐는데
발견한 것도 대단하네ㅋ 수고했으@

**Comment by ArtBlnd** [comment]
ㅂㄷㅂㄷ;;; VS 디버깅의 10퍼센트도 사용안하시는 당신을 미워합니다!

**Comment by ArtBlnd** [comment]
저 이레뵈도 VS 7년만짐!!

**Comment by ArtBlnd** [comment]
문제는 이제 저게 순수가상함수라. 후킹을 좀 정교하게 해야됨. 함수값을 구할수있는게 아님.(GetProcAddress로)

**Comment by sunghwan2789** [comment]
군 면접 갔다오고 추가함.
의외로 오디오 라이브러리 후킹이 어려운 게 아니더만!
