### ISSUE TITLE
queue 대신 뮤택스 도입 후 osu!가 멈춤

### ISSUE THREAD

**Issue by sunghwan2789** [sunghwan2789/osu-Lyrics#19]
6950db463db4af00992405c590351affeb5e34b5 의 빌드로 확인함...

**Comment by ArtBlnd** [comment]
엇... 전 아무문제없던데 곧 확잉해볼게요

**Comment by sunghwan2789** [comment]
이건 어떰?

**Comment by sunghwan2789** [comment]
밖이라 rdp로 확인해서 멈췄을 수도 있음

**Comment by ArtBlnd** [comment]
저 10분뒤부터 컴퓨터 만질수잇어서 잠시만 기다려줘요 ㅠㅠ

**Comment by sunghwan2789** [comment]
안 되면 그냥 mutex 갖다 버리고 다시 winapi에 critical_section 쓰는 거로...
파일 크기가 너무 커졌으..ㅋㅋ

**Comment by ArtBlnd** [comment]
파일크기가 커진건 디버그로 빌드해서그런거죠 std는 디버그함수가 많음.;;
제생각엔 이게지금 님이 수정한 코드에 문제가있음 제꺼로는잘됨
님이 수정한코드로하면안됨

**Comment by sunghwan2789** [comment]
릴리즈 모드인데 dll 크기가 두 배 커져서 써봤고..ㅎㅎ
블랜드가 manualHook에 풀한 코드로는 잘 되나?

**Comment by ArtBlnd** [comment]
ㅎㄹ.. 릴리즌데 2배커지다니... 그거  아직 진행도안함 정보찾아보면서 일주일동안할생각.
일단 이것부터해결함

**Comment by sunghwan2789** [comment]
그니까 그 브런치 빌드하면 잘 되남?

**Comment by ArtBlnd** [comment]
아 한번해볼게요

**Comment by ArtBlnd** [comment]
네 일단 오류는 안나나요.
근데 이쪽은 이쪽 나름대로 버그가있네요. 크레쉬는 안나는데 메세지를 보네도 C#에서 처리를 못함

**Comment by sunghwan2789** [comment]
bPipeConnected 대입식을 전으로 돌리니까 되긴하는데
바로 윗글처럼 osu!Lyrics로 메세지를 보내지 않음
또 이건 진짜 이상한 건데..
ConnecteNamedPipe는 0 반환해도 연결된 때가 있다는 거..
bPipeConnected = (ConnectNamedPipe() || GetLastError() == ERROR_PIPE_CONNECTED)
로 해야 어폐가 없거든...

결론은 뮤택스 큐가 잘못했네

**Comment by ArtBlnd** [comment]
ㅎㄹ... 좀더 나은방향으로 수정하겟습니다! 잠시만기다려주세요...

**Comment by ArtBlnd** [comment]
제생각엔 hkReadFile 함수를 동시에 osu의 다른스레드에서 접속해서 데드락이된것같네요. 수정할게요 잠시만기다려줘요!

**Comment by sunghwan2789** [comment]
뮤택스 큐를 위한 뮤택스??ㅋ

**Comment by sunghwan2789** [comment]
최대한 플레이에 영향 안 주게 짜 쥬

**Comment by ArtBlnd** [comment]
아시겟지만 이레서 메뉴얼이 힘듬 근데 재밌음!

**Comment by ArtBlnd** [comment]
아읗흐흫... queue 이터레이터 메모리때문에 고생하고있습니다 시간을 좀만 더 주시죠

**Comment by ArtBlnd** [comment]
deque iterator not dereferencable 이것때문에...ㅠㅠ

**Comment by ArtBlnd** [comment]
이게 디버그가 되면 고치기가쉬운데 후킹이라 디버깅이...ㅇ누마헝ㄴ멓앟

**Comment by sunghwan2789** [comment]
파이팅ㅋㅋ

**Comment by ArtBlnd** [comment]
이런씨;발 리빌드하니까 돼 아씨발 아ㅓ먀러댜ㅐㅁ저ㅐ댜ㅓㄱ먀ㅐㅈ더갸ㅐㅁ저ㅑㅐㄷㄹ검ㅈ
 4시간동안 뭐한거야 ㅠㅁㅇㅎㄻㅈㄷㄱㅁㅈㄷㄱ

**Comment by ArtBlnd** [comment]
ㅏ어마ㅣㄹㅇ너ㅏㅣㅓㅏㄴ아아아 울거야 ㅜㅜㅁ륨ㄹㅇㅍㅁ

**Comment by ArtBlnd** [comment]
리빌드하니까 돼 코드 분명 100퍼센트 맞는데 왜그러나했어

**Comment by ArtBlnd** [comment]
그와중에 반응속도 더올라감 ㅋㅋㅋ
너무 코드 다시짜고 다시짜고 다시짜고해서
