### ISSUE TITLE
오스를 mp3 플레이어로 사용하는 사람들 또는 창모드로 사용하는 사람들을 위한 기능!

### ISSUE THREAD

**Issue by ArtBlnd** [sunghwan2789/osu-Lyrics#21]
창으로 설정하면 폼 가이드가 생기고 움직일수있게 할수있으면 어떨까요? 움직인후에 고정하면 폼 가이드 사라지고 다시 클릭안되게!

**Comment by ArtBlnd** [comment]
PS. 블켓님도 이제 C# 수정 일하러가셔야죠! 후후후...

**Comment by sunghwan2789** [comment]
아니 이제 내일 준비할 건데...ㅋㅋㅋㅋ
그 기능은 생각해봄
준비되면 새 브랜치 만들어서 작업해야지

**Comment by ArtBlnd** [comment]
크흑!! 멋져부려!
