### ISSUE TITLE
가사 다운로드

### ISSUE THREAD

**Issue by ArtBlnd** [sunghwan2789/osu-Lyrics#24]
곡을 고르고나서 가사가 전부 다운로드전에 다른곡으로 넘겨도 전가사를 같이 다운받는것같네요.
표시는아닌데 다운받는게 안 멈추는것같음.

**Comment by sunghwan2789** [comment]
일부러 그럼

**Comment by sunghwan2789** [comment]
5f800482448b84c106db8e3a1c4a7c1c521fa34c
