### ISSUE TITLE
New Hooking Engine

### ISSUE THREAD

**Issue by ArtBlnd** [sunghwan2789/osu-Lyrics#26]
새로운 Bass 라이브러리 후킹안입니다.

함수는

BASS_StreamCreate -> 스트림을 만듭니다.
BASS_ChannelPlay -> 플레이합니다.
BASS_ChannelPause -> 일시중지합니다.
BASS_ChannelPause + Base_ChanelSetPosition to Zero -> 정지합니다.

일단 폐피에게 허락메일 보네놨습니다.
테스트는 이미 완료한 상태고 허락이 된다면 다시 제작하도록할게요.

**Comment by ArtBlnd** [comment]
만약에 허락이 되고 제작한다고하면.
더이상 기존의 이상한 방법으로 포지션을 구하지 않아도됩니다(?)

**Comment by sunghwan2789** [comment]
#25 로 확인했고, 347256cfdbd3676599e34da169356380cda5c075 로 해결함!
