### ISSUE TITLE
알송 서버 업데이트 가능할까요?

### ISSUE THREAD

**Issue by mirusu400** [sunghwan2789/osu-Lyrics#36]
최근에 사용해보고 싶어서 다시 해보니까 모든 곡에서 가사를 가져오질 못하네요.
대충 검색해보니 알송에서 가사를 주고받는 시스템이 바뀌었다는데..
혹시 수정 가능하신지 여쭤봅니다.

참고
http://blog.oshimari.com/221561467582

**Comment by ArtBlnd** [comment]
시간나면 볼게요
