### ISSUE TITLE
서버 dll 에서 Pipe가 Disconnected 됬음에도 불구하고. 패치를 안 푸셧네요.

### ISSUE THREAD

**Issue by ArtBlnd** [sunghwan2789/osu-Lyrics#4]
Disconnect 되면 패치 푸시고. 전에 Patch 용으로 사용했던 메모리 VirtualFree 해주셔야되요

**Comment by ArtBlnd** [comment]
- 이것도 블켓 팀으로 이동해주시면 수정할게요

**Comment by sunghwan2789** [comment]
포크하고 풀 리퀘스트 부탁..!

**Comment by ArtBlnd** [comment]
ㅅㄽㄽㄽㄹ 나도 같이프로젝트하고싶단말야!
안옾겨주면 일 안해!! 파업투쟁!!! 이야야야야얍

**Comment by sunghwan2789** [comment]
아.. 포크는 안 해도 되나..
잘 아는 것 같으니 부탁한담!(다른 거 하러 ㅌㅌ)

**Comment by ArtBlnd** [comment]
블켓팀으로 안옾겨주면 안해!!! 파업파업!
