### ISSUE TITLE
디버깅하는데 왜이렇게 Exception이 오질라게뜸.

### ISSUE THREAD

**Issue by ArtBlnd** [sunghwan2789/osu-Lyrics#9]
다고쳐주셈. 설명하기는 귀찮음 프로젝트 권환주면 알려줌

**Comment by ArtBlnd** [comment]
디버깅, 유지보수하기 극혐으로 만들어놨네 이런썅

**Comment by sunghwan2789** [comment]
ㅎㅎ;;

**Comment by ArtBlnd** [comment]
이거 정상적으로 자막들이 받아지고있는지 알수가없어요. 디버그하면 Exception이 계속떠서 계속 프리징되고. 문제가 어디있는지 알수가없음. 내부분은 잘돌아가고있어요. Windows 10임
